const student=["Subrat","subrat1","subrat2","subrat3"];
// console.log(student[0] );
// student.push("Subrat4");
// console.log(student);
// const newarr=[1,2,"car","🍾"];
// newarr.push({name:"Subrat2024"});
// student.reverse();
// console.log(student);
 student.forEach((val) => console.log(val));
 student.map((val)=>console.log(val));